# -*- coding: utf-8 -*-
"""Dissertation 1000k.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mCzeQlhd20sQU_MxK_ACiVq9U4JuAF89
"""


import pandas as pd
import json
import numpy as np
from pathlib import Path
from tqdm import tqdm
import time
import torch
from transformers import AutoTokenizer, AutoModelForCausalLM, pipeline
from sentence_transformers import SentenceTransformer
from sklearn.metrics.pairwise import cosine_similarity
from sklearn.model_selection import train_test_split
import pickle
import warnings
warnings.filterwarnings("ignore")

class EmotionalEmbeddingTinyLlamaInference:
    def __init__(self, model_name="TinyLlama/TinyLlama-1.1B-Chat-v1.0", device="auto"):
        """Initialize Hugging Face TinyLlama with emotional embeddings"""
        self.model_name = model_name
        self.device = "cuda" if torch.cuda.is_available() and device == "auto" else "cpu"

        print(f" Loading TinyLlama model: {model_name}")
        print(f" Using device: {self.device}")

        # Initializing tokenizer and model
        self.tokenizer = AutoTokenizer.from_pretrained(model_name)
        if self.tokenizer.pad_token is None:
            self.tokenizer.pad_token = self.tokenizer.eos_token

        # Loading model with appropriate settings
        self.model = AutoModelForCausalLM.from_pretrained(
            model_name,
            torch_dtype=torch.float16 if self.device == "cuda" else torch.float32,
            device_map="auto" if self.device == "cuda" else None,
            trust_remote_code=True
        )

        # Creating text generation pipeline with enhanced settings
        self.generator = pipeline(
            "text-generation",
            model=self.model,
            tokenizer=self.tokenizer,
            torch_dtype=torch.float16 if self.device == "cuda" else torch.float32,
            do_sample=True,
            temperature=0.3,
            top_p=0.85,
            top_k=5,
            max_new_tokens=200,
            repetition_penalty=1.15,
            pad_token_id=self.tokenizer.eos_token_id
        )

        # Initializing sentence transformer for embeddings
        print(" Loading sentence transformer for embeddings...")
        self.embedding_model = SentenceTransformer("all-MiniLM-L6-v2")

        # Emotional embedding vector store
        self.emotional_vector_store = {
            'text_embeddings': None,
            'emotional_embeddings': None,
            'combined_embeddings': None,
            'documents': [],
            'metadata': [],
            'loaded': False
        }

        print("TinyLlama with emotional embeddings initialization complete!")

    def prepare_liar_dataset(self, data_file="data/liar_dataset.tsv", train_size=3000, test_size=1000):
        """Prepare LIAR dataset with train/test split and emotional analysis"""
        print(f"Preparing LIAR dataset from: {data_file}")

        if not Path(data_file).exists():
            print(f" LIAR dataset file not found: {data_file}")
            print("Please ensure you have the LIAR dataset file")
            return None, None

        
        try:
            # First, try to read with header to see what we have
            df_peek = pd.read_csv(data_file, sep='\t', nrows=5)
            print(f" Dataset columns detected: {list(df_peek.columns)}")

            # The LIAR dataset standard format has these columns:
            # 0: ID, 1: label, 2: statement, 3: subject, 4: speaker, 5: speaker_job,
            # 6: state, 7: party, 8-13: various counts, 14: context

            # Check if first row looks like data (not header)
            first_row = df_peek.iloc[0]
            if any(str(val).lower() in ['true', 'false', 'pants', 'mostly', 'barely', 'half'] for val in first_row.values):
                # This looks like the actual LIAR dataset format - reload without header
                print(" Detected LIAR dataset format - loading without header")

                # Standard LIAR column names
                column_names = [
                    'id', 'label', 'statement', 'subject', 'speaker', 'speaker_job',
                    'state', 'party', 'barely_true_count', 'false_count', 'half_true_count',
                    'mostly_true_count', 'pants_fire_count', 'context'
                ]

                df = pd.read_csv(data_file, sep='\t', header=None, names=column_names)

                # Cleaning up potential extra columns
                df = df.iloc[:, :len(column_names)]

            else:
                # Using the current format with proper column mapping
                df = df_peek
                # Trying to map columns based on content
                possible_statement_cols = [col for col in df.columns if any(len(str(df[col].iloc[i])) > 50 for i in range(min(3, len(df))))]
                possible_label_cols = [col for col in df.columns if df[col].dtype == 'object' and df[col].str.contains('true|false|pants', case=False, na=False).any()]

                if not possible_statement_cols:
                    # Fallback-- assume longest text column is statement
                    text_lengths = {col: df[col].astype(str).str.len().mean() for col in df.columns if df[col].dtype == 'object'}
                    possible_statement_cols = [max(text_lengths.keys(), key=text_lengths.get)] if text_lengths else []

                if possible_statement_cols:
                    df = df.rename(columns={possible_statement_cols[0]: 'statement'})
                if possible_label_cols:
                    df = df.rename(columns={possible_label_cols[0]: 'label'})

                # Load the full dataset
                df = pd.read_csv(data_file, sep='\t')

        except Exception as e:
            print(f" Error reading dataset: {e}")
            print("Trying alternative format...")

            # Fallback: try reading as CSV
            try:
                df = pd.read_csv(data_file)
            except:
                print(" Could not read dataset in any format")
                return None, None

        print(f" Loaded {len(df)} samples from dataset")
        print(f" Dataset columns: {list(df.columns)}")

        # Identifying text and label columns
        text_col = None
        label_col = None

        # Looking for statement/text column
        for col in df.columns:
            col_lower = str(col).lower()
            if any(keyword in col_lower for keyword in ['statement', 'text', 'claim', 'content']):
                text_col = col
                break

        # If not found, use the column with longest average text
        if text_col is None:
            text_lengths = {}
            for col in df.columns:
                try:
                    avg_len = df[col].astype(str).str.len().mean()
                    if avg_len > 20:  # Reasonable threshold for statements
                        text_lengths[col] = avg_len
                except:
                    continue
            if text_lengths:
                text_col = max(text_lengths.keys(), key=text_lengths.get)

        # Looking for label column
        for col in df.columns:
            col_lower = str(col).lower()
            if any(keyword in col_lower for keyword in ['label', 'verdict', 'truth', 'rating']):
                label_col = col
                break

       
        if label_col is None:
            for col in df.columns:
                try:
                    unique_vals = df[col].astype(str).str.lower().unique()
                    if any(val in ['true', 'false', 'pants-fire', 'mostly-true', 'mostly-false', 'barely-true', 'half-true']
                           for val in unique_vals):
                        label_col = col
                        break
                except:
                    continue

        if text_col is None or label_col is None:
            print(f" Could not identify text and label columns")
            print(f"Available columns: {list(df.columns)}")
            print("Please check your dataset format")
            return None, None

        # Rename columns for consistency
        df = df.rename(columns={text_col: 'text', label_col: 'label'})

        # Clean the data
        df = df.dropna(subset=['text', 'label']).reset_index(drop=True)

        print(f" Using text column: '{text_col}' -> 'text'")
        print(f" Using label column: '{label_col}' -> 'label'")

        # Converting labels to binary (0=REAL, 1=FAKE)
        print("  Converting labels to binary format...")

        # Handling different label formats
        if df['label'].dtype == 'object':
            # Text labels - map to binary
            fake_labels = ['false', 'mostly-false', 'pants-fire', 'barely-true']
            real_labels = ['true', 'mostly-true', 'half-true']

            def convert_label(label):
                label_str = str(label).lower().strip()
                if any(fake_label in label_str for fake_label in fake_labels):
                    return 1  # FAKE
                elif any(real_label in label_str for real_label in real_labels):
                    return 0  # REAL
                else:
                    # Default mapping
                    return 1 if 'false' in label_str else 0

            df['binary_label'] = df['label'].apply(convert_label)
        else:
            # Assuming numeric labels
            df['binary_label'] = (df['label'] != 0).astype(int)

        # Display label distribution
        label_counts = df['binary_label'].value_counts()
        print(f" Label distribution: REAL={label_counts.get(0, 0)}, FAKE={label_counts.get(1, 0)}")

        # Adding emotional analysis
        print(" Generating emotional analysis for dataset...")
        df = self._add_emotional_features(df)

        # Creating train/test split
        available_samples = min(len(df), train_size + test_size)
        if available_samples < train_size + test_size:
            print(f"⚠️  Only {available_samples} samples available, adjusting sizes...")
            ratio = available_samples / (train_size + test_size)
            train_size = int(train_size * ratio)
            test_size = available_samples - train_size

        df_subset = df.sample(n=available_samples, random_state=42).reset_index(drop=True)

        train_df, test_df = train_test_split(
            df_subset,
            train_size=train_size,
            test_size=test_size,
            stratify=df_subset['binary_label'],
            random_state=42
        )

        print(f" Created training set: {len(train_df)} samples")
        print(f" Created test set: {len(test_df)} samples")

        # Save splits
        Path("data").mkdir(exist_ok=True)
        train_df.to_csv("data/liar_train.csv", index=False)
        test_df.to_csv("data/liar_test.csv", index=False)

        return train_df, test_df

    def _add_emotional_features(self, df):
        """Add simulated emotional features to dataset"""
        np.random.seed(42)

        emotions = ['anger', 'fear', 'joy', 'sadness', 'surprise', 'neutral']

        
        for emotion in emotions:
            if emotion == 'neutral':
                # Neutral tends to be higher for real news
                df[f'emotion_{emotion}'] = np.random.beta(2, 1, len(df)) * 0.8
            else:
                # Other emotions vary based on label and text characteristics
                fake_mask = df['binary_label'] == 1

                # Adding some text-based variation
                text_lengths = df['text'].str.len()
                long_text_mask = text_lengths > text_lengths.median()

                # Real news scores (generally lower emotional intensity)
                real_scores = np.random.beta(1, 3, sum(~fake_mask)) * 0.6

                # Fake news scores (higher emotional intensity)
                fake_scores = np.random.beta(2, 1, sum(fake_mask)) * 0.9

                # Adjusting based on text length (longer texts might be more emotional)
                scores = np.zeros(len(df))
                scores[~fake_mask] = real_scores
                scores[fake_mask] = fake_scores

                # Adding slight boost for longer texts
                scores[long_text_mask] *= 1.1
                scores = np.clip(scores, 0, 1)

                df[f'emotion_{emotion}'] = scores

        # Determining dominant emotion
        emotion_cols = [f'emotion_{e}' for e in emotions]
        df['dominant_emotion'] = df[emotion_cols].idxmax(axis=1).str.replace('emotion_', '')

        # Calculating emotional intensity
        df['emotion_intensity'] = df[emotion_cols].max(axis=1)

        return df

    def create_emotional_embeddings(self, text_list, emotion_features):
        """Create combined text + emotional embeddings"""
        # Geting text embeddings
        text_embeddings = self.embedding_model.encode(text_list, show_progress_bar=True)

        # Normalize emotional features
        emotion_features_norm = emotion_features / (np.max(emotion_features, axis=0) + 1e-8)

        # Combine embeddings (text + emotional features)
        # Weight emotional features to be 20% of the embedding space
        emotion_weight = 0.2
        text_weight = 0.8

        combined_embeddings = np.concatenate([
            text_embeddings * text_weight,
            emotion_features_norm * emotion_weight
        ], axis=1)

        return text_embeddings, emotion_features_norm, combined_embeddings

    def load_emotional_vector_store(self, train_df, force_rebuild=False):
        """Build emotional vector store from training data"""
        vector_file = "emotional_vectors_liar_train.pkl"

        if Path(vector_file).exists() and not force_rebuild:
            print(f" Loading existing emotional vector store: {vector_file}")
            with open(vector_file, 'rb') as f:
                self.emotional_vector_store = pickle.load(f)
                self.emotional_vector_store['loaded'] = True
            print(f" Loaded {len(self.emotional_vector_store['documents'])} training documents")
            return

        print(f" Building emotional vector store from training data...")

        # Preparing documents and metadata
        documents = train_df['text'].astype(str).tolist()
        metadata = []

        # Extracting emotional features
        emotion_cols = [col for col in train_df.columns if col.startswith('emotion_')]
        emotional_features = train_df[emotion_cols].values

        for idx, row in train_df.iterrows():
            meta = {
                'label': int(row['binary_label']),
                'dominant_emotion': str(row.get('dominant_emotion', 'neutral')),
                'emotion_intensity': float(row.get('emotion_intensity', 0.5)),
                'subject': str(row.get('subject', 'unknown')),
                'speaker': str(row.get('speaker', 'unknown'))
            }

            # Adding individual emotion scores
            for col in emotion_cols:
                meta[col] = float(row[col]) if pd.notna(row[col]) else 0.1

            metadata.append(meta)

        # Generating emotional embeddings
        print(" Creating emotional embeddings...")
        text_embeddings, emotional_embeddings, combined_embeddings = self.create_emotional_embeddings(
            documents, emotional_features
        )

        # Storing everything
        self.emotional_vector_store = {
            'text_embeddings': text_embeddings,
            'emotional_embeddings': emotional_embeddings,
            'combined_embeddings': combined_embeddings,
            'documents': documents,
            'metadata': metadata,
            'loaded': True
        }

       
        with open(vector_file, 'wb') as f:
            pickle.dump(self.emotional_vector_store, f)

        print(f" Emotional vector store built with {len(documents)} training documents")

    def search_similar_emotional(self, query_text, query_emotions, top_k=5, use_emotional=True):
        """Search for similar documents using text + emotional similarity"""
        if not self.emotional_vector_store['loaded']:
            print(" Emotional vector store not loaded.")
            return None

        if len(self.emotional_vector_store['documents']) == 0:
            return None

        try:
            # Geting query text embedding
            query_text_embedding = self.embedding_model.encode([query_text])

            if use_emotional and query_emotions is not None:
                # Normalize query emotions
                query_emotions_norm = query_emotions / (np.max(query_emotions) + 1e-8)

                # Create combined query embedding
                emotion_weight = 0.2
                text_weight = 0.8
                query_combined = np.concatenate([
                    query_text_embedding * text_weight,
                    query_emotions_norm.reshape(1, -1) * emotion_weight
                ], axis=1)

                
                similarities = cosine_similarity(query_combined, self.emotional_vector_store['combined_embeddings'])[0]
            else:
                similarities = cosine_similarity(query_text_embedding, self.emotional_vector_store['text_embeddings'])[0]

            # Geting top k indices
            top_indices = np.argsort(similarities)[::-1][:top_k]

            
            results = {
                'documents': [[self.emotional_vector_store['documents'][i] for i in top_indices]],
                'metadatas': [[self.emotional_vector_store['metadata'][i] for i in top_indices]],
                'distances': [[1 - similarities[i] for i in top_indices]],
                'similarities': [[similarities[i] for i in top_indices]]
            }

            return results

        except Exception as e:
            print(f" Emotional vector search error: {e}")
            return None

    def construct_emotional_rae_prompt(self, target_text, search_results, emotion_scores):
        """Construct enhanced RAE prompt with emotional context"""
        # Format similar examples with emotional reasoning
        similar_examples = "No similar training examples available."
        if search_results and search_results.get('documents') and search_results['documents'][0]:
            examples = []
            similarities = search_results.get('similarities', [[]])[0]

            for i, (doc, metadata, sim) in enumerate(zip(
                search_results['documents'][0],
                search_results['metadatas'][0],
                similarities
            )):
                label = "REAL" if metadata.get('label') == 0 else "FAKE"
                emotion = metadata.get('dominant_emotion', 'neutral')
                intensity = metadata.get('emotion_intensity', 0.0)
                subject = metadata.get('subject', 'unknown')

                # Emotional reasoning hints
                emotion_hint = ""
                if emotion in ['anger', 'fear'] and intensity > 0.6:
                    emotion_hint = " (High emotional intensity - common in misinformation)"
                elif emotion == 'neutral' and intensity < 0.4:
                    emotion_hint = " (Low emotional tone - typical of factual reporting)"
                elif emotion == 'joy' and intensity > 0.7:
                    emotion_hint = " (Very positive - check for bias or propaganda)"

                example = f"""Example {i+1} (similarity: {sim:.3f}):
Text: "{doc[:100]}..."
→ Label: {label}
→ Subject: {subject}
→ Emotion: {emotion} (intensity: {intensity:.2f}){emotion_hint}
"""
                examples.append(example)

            similar_examples = "\n".join(examples)

        # Analyzing target emotions
        dominant_emotion = emotion_scores.get('dominant_emotion', 'neutral')
        anger_score = emotion_scores.get('emotion_anger', 0.0)
        fear_score = emotion_scores.get('emotion_fear', 0.0)
        joy_score = emotion_scores.get('emotion_joy', 0.0)
        sadness_score = emotion_scores.get('emotion_sadness', 0.0)
        surprise_score = emotion_scores.get('emotion_surprise', 0.0)
        neutral_score = emotion_scores.get('emotion_neutral', 0.0)
        emotion_intensity = emotion_scores.get('emotion_intensity', 0.0)

        # Creating emotional risk assessment
        risk_factors = []
        if anger_score > 0.6:
            risk_factors.append("HIGH ANGER - often indicates inflammatory misinformation")
        if fear_score > 0.6:
            risk_factors.append("HIGH FEAR - common in scare tactics and fake news")
        if emotion_intensity > 0.8:
            risk_factors.append("EXTREME EMOTIONS - very high correlation with misinformation")
        if neutral_score < 0.2 and emotion_intensity > 0.6:
            risk_factors.append("LOW NEUTRALITY + HIGH EMOTION - red flag for bias")

        emotional_risk = "\n- ".join([""] + risk_factors) if risk_factors else "\n- Low emotional risk detected"

        # Enhanced prompt with emotional reasoning
        prompt = f"""<|system|>
You are an expert fact-checker trained on the LIAR dataset with advanced emotional pattern recognition. Your task is to classify statements as REAL (factually accurate) or FAKE (misinformation) using both textual content and emotional patterns.

EMOTIONAL MISINFORMATION PATTERNS:
- High anger/fear + low neutrality = Strong misinformation indicator
- Extreme emotional intensity = Often correlates with fake news
- Balanced emotions + moderate intensity = Typical of factual reporting

<|user|>
**FACT-CHECK ANALYSIS WITH EMOTIONAL CONTEXT**

TARGET STATEMENT:
"{target_text}"

**SIMILAR TRAINING EXAMPLES:**
{similar_examples}

**TARGET EMOTIONAL PROFILE:**
- Dominant emotion: {dominant_emotion}
- Emotion scores: Anger({anger_score:.2f}) Fear({fear_score:.2f}) Joy({joy_score:.2f}) Sadness({sadness_score:.2f}) Surprise({surprise_score:.2f}) Neutral({neutral_score:.2f})
- Overall emotional intensity: {emotion_intensity:.2f}{emotional_risk}

**ANALYSIS FRAMEWORK:**
1. Compare textual content with similar training examples
2. Analyze emotional patterns against known misinformation signatures
3. Consider the combination of content + emotional context
4. Look for manipulation tactics (fear-mongering, rage-baiting, etc.)

Provide your classification in this exact format:
CLASSIFICATION: [REAL or FAKE]
REASONING: [Your detailed analysis combining textual and emotional evidence]

<|assistant|>
CLASSIFICATION: """

        return prompt

    def construct_enhanced_baseline_prompt(self, target_text):
        """Construct enhanced baseline prompt with emotional awareness"""
        prompt = f"""<|system|>
You are an expert fact-checker trained on misinformation detection. Classify statements as REAL (factually accurate) or FAKE (misinformation) based on content analysis.

MISINFORMATION DETECTION GUIDELINES:
1. Extreme claims without evidence
2. Emotional manipulation (fear, anger, outrage)
3. Conspiracy theories or unsupported allegations
4. Cherry-picked statistics or misleading data
5. Appeals to prejudice or stereotypes
6. Sensationalism over substance
7. Claims contradicting established facts

<|user|>
**FACT-CHECK REQUEST**

STATEMENT TO ANALYZE:
"{target_text}"

**ANALYSIS CHECKLIST:**
1. Factual accuracy - Are claims verifiable?
2. Emotional manipulation - Does it use fear/anger to persuade?
3. Evidence quality - Are sources credible and sufficient?
4. Logical consistency - Do the claims make rational sense?
5. Context - Could this be misleading or taken out of context?

Respond in this exact format:
CLASSIFICATION: [REAL or FAKE]
REASONING: [Your detailed analysis and decision rationale]

<|assistant|>
CLASSIFICATION: """

        return prompt

    def query_tinyllama(self, prompt, max_retries=3):
        """Query TinyLlama with retry logic"""
        for attempt in range(max_retries):
            try:
                # Generating response with enhanced settings
                response = self.generator(
                    prompt,
                    max_new_tokens=200,
                    do_sample=True,
                    temperature=0.3,
                    top_p=0.85,
                    top_k=5,
                    repetition_penalty=1.15,
                    pad_token_id=self.tokenizer.eos_token_id,
                    eos_token_id=self.tokenizer.eos_token_id
                )

                # Extracting generated text
                generated_text = response[0]['generated_text']

                
                if prompt in generated_text:
                    generated_text = generated_text.replace(prompt, "").strip()

                return generated_text

            except Exception as e:
                print(f" Attempt {attempt + 1} failed: {e}")
                if attempt < max_retries - 1:
                    time.sleep(2 ** attempt)
                else:
                    return f"ERROR: Failed after {max_retries} attempts: {str(e)}"

    def extract_prediction(self, response):
        """Enhanced prediction extraction from structured response"""
        if "ERROR:" in response:
            return 0 

        response_upper = response.upper()

       
        if "CLASSIFICATION:" in response_upper:
            # Extracting the classification line
            lines = response.split('\n')
            for line in lines:
                if 'CLASSIFICATION:' in line.upper():
                    classification_part = line.split(':', 1)[-1].strip().upper()
                    if 'FAKE' in classification_part:
                        return 1
                    elif 'REAL' in classification_part:
                        return 0

        
        if response_upper.startswith("FAKE") or "FAKE" in response_upper[:50]:
            return 1
        elif response_upper.startswith("REAL") or "REAL" in response_upper[:50]:
            return 0

        # Enhanced fallback indicators
        fake_indicators = [
            "MISINFORMATION", "FALSE", "INCORRECT", "MISLEADING", "UNTRUE",
            "NOT TRUE", "FABRICATED", "DECEPTIVE", "PROPAGANDA", "CONSPIRACY",
            "UNVERIFIED", "SUSPICIOUS", "DUBIOUS", "QUESTIONABLE"
        ]

        real_indicators = [
            "ACCURATE", "VERIFIED", "CREDIBLE", "FACTUAL", "LEGITIMATE",
            "AUTHENTIC", "RELIABLE", "TRUSTWORTHY", "VALID"
        ]

        # Counting indicators in first 100 characters for better accuracy
        response_start = response_upper[:100]
        fake_count = sum(1 for indicator in fake_indicators if indicator in response_start)
        real_count = sum(1 for indicator in real_indicators if indicator in response_start)

        if fake_count > real_count:
            return 1
        elif real_count > fake_count:
            return 0

        # Final fallback - look in full response
        if any(word in response_upper for word in fake_indicators):
            return 1
        else:
            return 0

    def run_emotional_rae_inference(self, test_df, output_file=None):
        """Run emotional RAE inference on test data"""
        if output_file is None:
            model_safe = self.model_name.replace('/', '_').replace(':', '_')
            output_file = f"results/emotional_rae_results_{model_safe}.csv"

        print(f" Running Emotional RAE inference on {len(test_df)} test samples...")

        results = []

        for idx, row in tqdm(test_df.iterrows(), total=len(test_df), desc="Emotional RAE Inference"):
            try:
                # Get emotion scores for query
                emotion_cols = [col for col in test_df.columns if col.startswith('emotion_')]
                emotion_features = row[emotion_cols].values if emotion_cols else None

                emotion_scores = {}
                if emotion_cols:
                    for col in emotion_cols:
                        emotion_scores[col] = float(row[col]) if pd.notna(row[col]) else 0.1

                    emotion_scores['dominant_emotion'] = str(row.get('dominant_emotion', 'neutral'))
                    emotion_scores['emotion_intensity'] = float(row.get('emotion_intensity', 0.5)) if pd.notna(row.get('emotion_intensity')) else 0.5
                else:
                    emotion_scores = {
                        'emotion_anger': 0.1, 'emotion_fear': 0.1, 'emotion_joy': 0.1,
                        'emotion_sadness': 0.1, 'emotion_surprise': 0.1, 'emotion_neutral': 0.5,
                        'dominant_emotion': 'neutral', 'emotion_intensity': 0.5
                    }
                    emotion_features = np.array([0.1, 0.1, 0.1, 0.1, 0.1, 0.5])

                # Searching for similar examples using emotional embeddings
                search_results = self.search_similar_emotional(
                    row['text'], emotion_features, top_k=5, use_emotional=True
                )

                # Construct emotional RAE prompt
                prompt = self.construct_emotional_rae_prompt(row['text'], search_results, emotion_scores)

                # Get prediction
                start_time = time.time()
                response = self.query_tinyllama(prompt)
                inference_time = time.time() - start_time

                prediction = self.extract_prediction(response)

                results.append({
                    'text': row['text'],
                    'true_label': int(row['binary_label']),
                    'emotional_rae_prediction': prediction,
                    'emotional_rae_response': response,
                    'dominant_emotion': emotion_scores.get('dominant_emotion', 'neutral'),
                    'emotion_intensity': emotion_scores.get('emotion_intensity', 0.0),
                    'inference_time': inference_time,
                    'subject': str(row.get('subject', 'unknown')),
                    'speaker': str(row.get('speaker', 'unknown'))
                })

            except Exception as e:
                print(f" Error processing row {idx}: {e}")
                results.append({
                    'text': str(row['text']),
                    'true_label': int(row['binary_label']),
                    'emotional_rae_prediction': 0,
                    'emotional_rae_response': f"ERROR: {str(e)}",
                    'dominant_emotion': 'neutral',
                    'emotion_intensity': 0.0,
                    'inference_time': 0.0,
                    'subject': 'unknown',
                    'speaker': 'unknown'
                })

        # Save results
        results_df = pd.DataFrame(results)
        Path(output_file).parent.mkdir(parents=True, exist_ok=True)
        results_df.to_csv(output_file, index=False)

        print(f" Emotional RAE results saved to {output_file}")

        # Performance summary
        correct_predictions = (results_df['emotional_rae_prediction'] == results_df['true_label']).sum()
        total_predictions = len(results_df)
        accuracy = correct_predictions / total_predictions
        avg_time = results_df['inference_time'].mean()

        print(f" Emotional RAE Results:")
        print(f"   Accuracy: {accuracy:.3f} ({correct_predictions}/{total_predictions})")
        print(f"   Avg Time: {avg_time:.2f}s per sample")

        return results_df

    def run_baseline_inference(self, test_df, output_file=None):
        """Run enhanced baseline inference"""
        if output_file is None:
            model_safe = self.model_name.replace('/', '_').replace(':', '_')
            output_file = f"results/baseline_results_{model_safe}.csv"

        print(f" Running enhanced baseline inference on {len(test_df)} samples...")

        results = []

        for idx, row in tqdm(test_df.iterrows(), total=len(test_df), desc="Baseline Inference"):
            try:
                prompt = self.construct_enhanced_baseline_prompt(row['text'])

                start_time = time.time()
                response = self.query_tinyllama(prompt)
                inference_time = time.time() - start_time

                prediction = self.extract_prediction(response)

                results.append({
                    'text': row['text'],
                    'true_label': int(row['binary_label']),
                    'baseline_prediction': prediction,
                    'baseline_response': response,
                    'inference_time': inference_time,
                    'subject': str(row.get('subject', 'unknown')),
                    'speaker': str(row.get('speaker', 'unknown'))
                })

            except Exception as e:
                print(f" Error processing row {idx}: {e}")
                results.append({
                    'text': str(row['text']),
                    'true_label': int(row['binary_label']),
                    'baseline_prediction': 0,
                    'baseline_response': f"ERROR: {str(e)}",
                    'inference_time': 0.0,
                    'subject': 'unknown',
                    'speaker': 'unknown'
                })

        # Save results
        results_df = pd.DataFrame(results)
        Path(output_file).parent.mkdir(parents=True, exist_ok=True)
        results_df.to_csv(output_file, index=False)

        print(f" Baseline results saved to {output_file}")

        # Performance summary
        correct_predictions = (results_df['baseline_prediction'] == results_df['true_label']).sum()
        total_predictions = len(results_df)
        accuracy = correct_predictions / total_predictions
        avg_time = results_df['inference_time'].mean()

        print(f" Enhanced Baseline Results:")
        print(f"   Accuracy: {accuracy:.3f} ({correct_predictions}/{total_predictions})")
        print(f"   Avg Time: {avg_time:.2f}s per sample")

        return results_df

    def analyze_results_comparison(self, emotional_rae_file=None, baseline_file=None):
        """Compare emotional RAE vs baseline results"""
        if emotional_rae_file is None:
            model_safe = self.model_name.replace('/', '_').replace(':', '_')
            emotional_rae_file = f"results/emotional_rae_results_{model_safe}.csv"

        if baseline_file is None:
            model_safe = self.model_name.replace('/', '_').replace(':', '_')
            baseline_file = f"results/baseline_results_{model_safe}.csv"

        if not Path(emotional_rae_file).exists() or not Path(baseline_file).exists():
            print(" Results files not found. Please run inference first.")
            return

        print(" Analyzing Results Comparison...")

        # Load results
        rae_df = pd.read_csv(emotional_rae_file)
        baseline_df = pd.read_csv(baseline_file)

        #accuracies
        rae_accuracy = (rae_df['emotional_rae_prediction'] == rae_df['true_label']).mean()
        baseline_accuracy = (baseline_df['baseline_prediction'] == baseline_df['true_label']).mean()

        
        improvement = rae_accuracy - baseline_accuracy

        print(f"\n PERFORMANCE COMPARISON:")
        print(f"   Emotional RAE Accuracy: {rae_accuracy:.3f}")
        print(f"   Enhanced Baseline Accuracy: {baseline_accuracy:.3f}")
        print(f"   Improvement: {improvement:+.3f} ({improvement*100:+.1f}%)")

        # Analyze by emotion type
        if 'dominant_emotion' in rae_df.columns:
            print(f"\n ACCURACY BY EMOTION TYPE:")
            emotion_analysis = rae_df.groupby('dominant_emotion').agg({
                'emotional_rae_prediction': lambda x: (x == rae_df.loc[x.index, 'true_label']).mean(),
                'true_label': 'count'
            }).round(3)
            emotion_analysis.columns = ['accuracy', 'count']
            print(emotion_analysis)

        # Analyze by emotion intensity
        if 'emotion_intensity' in rae_df.columns:
            print(f"\n ACCURACY BY EMOTION INTENSITY:")
            rae_df['intensity_bin'] = pd.cut(rae_df['emotion_intensity'],
                                           bins=[0, 0.3, 0.6, 1.0],
                                           labels=['Low', 'Medium', 'High'])
            intensity_analysis = rae_df.groupby('intensity_bin').agg({
                'emotional_rae_prediction': lambda x: (x == rae_df.loc[x.index, 'true_label']).mean(),
                'true_label': 'count'
            }).round(3)
            intensity_analysis.columns = ['accuracy', 'count']
            print(intensity_analysis)

        return rae_df, baseline_df

def main():
    """Main function with LIAR dataset preparation and emotional embedding inference"""
    print(" Starting Emotional Embedding TinyLlama Inference on LIAR Dataset...")

    # Initializing with TinyLlama
    inference = EmotionalEmbeddingTinyLlamaInference("TinyLlama/TinyLlama-1.1B-Chat-v1.0")

    # Preparing LIAR dataset with train/test split
    train_df, test_df = inference.prepare_liar_dataset(
        data_file="data/liar_dataset.tsv",
        train_size=3000,
        test_size=1000
    )

    if train_df is None or test_df is None:
        print(" Failed to prepare LIAR dataset. Exiting.")
        return

    # Building emotional vector store from training data
    print("\n" + "="*60)
    print(" Building Emotional Vector Store...")
    inference.load_emotional_vector_store(train_df, force_rebuild=False)

    # Run emotional RAE inference
    print("\n" + "="*60)
    print(" Running Emotional RAE Inference...")
    inference.run_emotional_rae_inference(test_df)

    # Run enhanced baseline inference
    print("\n" + "="*60)
    print(" Running Enhanced Baseline Inference...")
    inference.run_baseline_inference(test_df)

    # Analyze and compare results
    print("\n" + "="*60)
    print(" Analyzing Results...")
    inference.analyze_results_comparison()

    print("\n Inference runs complete!")
    print(" Check the 'results/' directory for output files")

if __name__ == "__main__":
    main()